version: '3.8'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - postgres
    networks:
      - auza-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-auza   
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    networks:
      - auza-network

  redis:
    image: redis:alpine
    container_name: redis-auza
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auza-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=AuzaUniversDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auza-network

networks:
  auza-network:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:  