version: '3.8'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
      - postgres
      - redis
    networks:
      - auza-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=AuzaUniversDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auza-network

  redis:
    image: redis:alpine
    container_name: redis-auza
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auza-network

networks:
  auza-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: