// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250508182953_edit model db")]
    partial class editmodeldb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entites.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DataAccess.Entites.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("DataAccess.Entites.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Auditorium")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("MentorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("GroupId");

                    b.HasIndex("MentorId");

                    b.ToTable("Pairs");
                });

            modelBuilder.Entity("DataAccess.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MyGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("MyPairId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MyGroupId");

                    b.HasIndex("MyPairId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GroupMentor", b =>
                {
                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("MentorsId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsId", "MentorsId");

                    b.HasIndex("MentorsId");

                    b.ToTable("GroupMentor");
                });

            modelBuilder.Entity("DataAccess.Entites.Pair", b =>
                {
                    b.HasOne("DataAccess.Entites.Group", "GroupPair")
                        .WithMany("Pairs")
                        .HasForeignKey("GroupId");

                    b.HasOne("DataAccess.Entites.Mentor", "Mentor")
                        .WithMany("Pairs")
                        .HasForeignKey("MentorId");

                    b.Navigation("GroupPair");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DataAccess.Entites.Student", b =>
                {
                    b.HasOne("DataAccess.Entites.Group", "MyGroup")
                        .WithMany("StudentsGroup")
                        .HasForeignKey("MyGroupId");

                    b.HasOne("DataAccess.Entites.Pair", "MyPair")
                        .WithMany("Students")
                        .HasForeignKey("MyPairId");

                    b.Navigation("MyGroup");

                    b.Navigation("MyPair");
                });

            modelBuilder.Entity("GroupMentor", b =>
                {
                    b.HasOne("DataAccess.Entites.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entites.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entites.Group", b =>
                {
                    b.Navigation("Pairs");

                    b.Navigation("StudentsGroup");
                });

            modelBuilder.Entity("DataAccess.Entites.Mentor", b =>
                {
                    b.Navigation("Pairs");
                });

            modelBuilder.Entity("DataAccess.Entites.Pair", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
