name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore UniversSystem/UniversSystem.csproj

    - name: Build
      run: dotnet build UniversSystem/UniversSystem.csproj --no-restore

    - name: Restore test project
      run: dotnet restore Tests/Tests.csproj

    - name: Build test project
      run: dotnet build Tests/Tests.csproj --no-restore

    - name: Run tests
      run: dotnet test Tests/Tests.csproj --no-build --verbosity normal
    
    - name: Run backend
      run: dotnet run --project UniversSystem/UniversSystem.csproj
